### ISSUE TITLE
New website domain

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-oslo/rdm-lookup#25]
Currently, it's based on lengthy repo name https://elixir-oslo.github.io/norwegian-life-sci-rdm-lookup/

Suggestions:
- rdm-lookup.elixir-no.org?
- life-sci-rdm.elixir-no.org?
- life-sci-rdm.no

**Comment by korbinib** [comment]
how about rdm-lookup.elixir.no ? (then we don't need a new elixir.no.org ;) )

@sveinugu could you help sorting this?

**Comment by Nazeeefa** [comment]
Let's sort out rdm-lookup.elixir.no

**Comment by sveinugu** [comment]
I think the best solution is to set up a reverse proxy on the elixir.no web server for this. @morj-uio should be able to sort this out. He is not working until next week, I believe. Is this urgent?

Also you should make sure that all the links are relative so that that the path part of the URL is not referred to anywhere.

GitHub pages has a solution for hosting on a remote domain, but that uses let's encrypt which uio do not support and that we are moving (very slowly) away from.

**Comment by Nazeeefa** [comment]
Yes this is urgent, thank you

**Comment by sveinugu** [comment]
I interpret from the fact that it took three whole days for you to answer that this is urgent, as well as not hearing anything about the urgency of this in Finse, that it is really not that urgent and can wait until @morj-uio comes to work next week (which was what I was asking about). 

Please reserve the word urgent to times when thing really are urgent (i.e. within the same day or the next), and also provide a deadline (and reason for this, e.g. presentation/reporting/whatever) so that we can actually use this information for something.. We have enough stress as is!

**Comment by Nazeeefa** [comment]
When I used the term urgent in this context, I took into account Morten's availability and meant that it would be nice if it is done soon once Morten is back. There is no strict definition of urgent used here as I am respectful to other people's schedule including mine. I did mention it during the meeting in Finse to which Korbinian responded that it's a secondary priority and that it will be nice to have something to link to - that concluded the conversation, in my opinion. Please kindly give a benefit of doubt and be respectful to your colleagues, that could make communication a lot less stressful. You are not the only one dealing with stress.

**Comment by sveinugu** [comment]
Urgent is defined as "requiring immediate action or attention".

I don't think it is disrespectful of me to inform you about how I and I believe others understand this word (which is according to its definition), on the contrary, I think that this is a respectful thing to do. However, this is not a good place to have this conversation and I see that I started it here and that it was thoughtless of me to respond in this context. I am sorry about that!

In any case, thanks for a great F2F and wishing you a nice weekend!

**Comment by Nazeeefa** [comment]
Thank you, and I am sorry for any misunderstanding/inconvenience caused from my side. Hope you reach home fine and have a relaxing weekend. Take care

**Comment by morj-uio** [comment]
Grrr, I had written many words, detailing different options, then clicked a link and lost it all.. Reminder to use email when replying to issues.

Anyway, as an example, I quickly set up this proxy instead:
https://elixir.no/norwegian-life-sci-rdm-lookup

Do you really need a new domain? It is not possible to hide the repo name/prefix anyway. It will be visible in menu links and search results etc, because they are root-relative. The GitHub custom domain option probably strips the prefix, but that is not possible with an external proxy solution. Can you shorten the repo name somewhat instead?

Of course we can order rdm-lookup.elixir.no anyway and use it as a shortcut/redirect to the above, optionally.

Btw, do we know where we are wrt UiO-certified certificates for elixir.no? Is it possible to get yet?

**Comment by morj-uio** [comment]
Then it will simply be elixir.no/rdm-lookup<http://elixir.no/rdm-lookup>. I think that is good as can be and will adjust the proxy config soon.

20. feb. 2023 kl. 15:55 skrev Nazeeefa ***@***.******@***.***>>:



Thanks @morj-uio<https://github.com/morj-uio> for setting up proxy.
I have shortened the repo name, hope that sort of helps.
